### ISSUE TITLE
Enhancements/bugs on the daily report form (GPS field, Mectizan to be changed to Ivermectine, and Conditional Rendering for treatments)

### ISSUE THREAD

**Issue by sangalvs** [ChangePlusPlusVandy/UFAR-frontend#22]
- GPS Field: Add a field on the data collection form where some API would get the location of the nurse and automatically show it there. Would be on the first page.
- Make sure everywhere it says "Mectizan" is changed to "Ivermectine." Ivermectine and Mectizan are the same drug but Ivermectine is the more recognized name for it in the DRC.
- Make sure the daily report form doesn't render the questions around certain treatments later on ProcessingForm if they weren't selected before on the TreatmentInformation part of the daily report form (i.e. if nothing was given about Mectizan + Albendazole in the TreatmentInformation page, then nothing should be rendered for it on the ProcessingForm in order to lower the amount of mistakes and save space too.)

**Comment by sparkeGH** [comment]
Mectizan replaced with ivermectine
