### ISSUE TITLE
Some small styling enhancements

### ISSUE THREAD

**Issue by ethanratnofsky** [ChangePlusPlusVandy/UFAR-frontend#24]
While @salomondush was demoing the functionality of the application so far, I noted a few styling enhancements that I think would significantly improve the look of the application:
-  **UFAR Logo Color**
The background of the UFAR logo on the home page is a slightly different color red than the background color we currently have implemented throughout the app. A fix for this would be either adjusting the color of the background in the image for the logo in photoshop or adjusting the background colors implemented in the app to the background color of the logo (use a color picker tool to find the exact hex value for the color).
- **Offline Mode Banner**
We might want to adjust the styling of the offline mode banner so that it is not cut off when the Daily Report Form is open.
![image](https://user-images.githubusercontent.com/43038541/150167902-b35ea6b3-b8e3-4995-b333-049bef9cd514.png)
- **Submit/Save Button Styling**
The submit/save button at the end of the Daily Report Form needs to be restyled so that it looks like the Next button in previous pages and looks like Asher's designs in Adobe XD.
- **List Styling**
A minor detail, but an improvement that can be made to the styling of the lists (reports/validations) is adding small margins so the drop shadows aren't cut off so sharply.
- **Persisted Offline Report Status Icon**
I believe the color of the icon for reports that need to be uploaded should be changed (possibly to yellow) to make them more distinct from reports that have already been uploaded and/or validated.

**Comment by sparkeGH** [comment]
Offline banner and submit button styling should be reolved on Issues branch; color choice tbd

**Comment by sparkeGH** [comment]
Margins on lists should be fixed (only RecentsList successfully rendered because I'm trapped in offline mode)

**Comment by sparkeGH** [comment]
Yellow icons for unsubmitted reports added

**Comment by sparkeGH** [comment]
Only small color changes remain, which are easily implemented and might not be needed for product
