### ISSUE TITLE
Identify Optional and Non-optional Fields On The Daily Report Form

### ISSUE THREAD

**Issue by salomondush** [ChangePlusPlusVandy/UFAR-frontend#3]
Conditional Rendering according to selected options:

Treatment information

- [ ]  Onchocercose
- [ ] Filariose lymphatique
- [ ] Schiostosomiase
- [ ] Gèohelminthiases
- [ ] Trachome

Treatement:
Show options according to what was selected: 

Ivermectin (Onchocercose)
Ivermectin et Albendazole (Filariose lymphatique)
Albendazole seul (Filariose lymphatique)
Praziquantel (Schistosomiase)
Albendazole (Géohelminthiases)

Drug management (Gestion des médicaments)
Ivermectine (Oncho/FL) -> Onchocercose/ Filariose lymphatique
Albendazole (FL/STH) -> Géohelminthiases/ Filariose lymphatique
Praziquantel (SCH) -> Schistosomiase

**Comment by sangalvs** [comment]
Everything is mandatory but don't prompt for treatment information from diseases that weren't mentioned for treatment cycles.
