### ISSUE TITLE
Make daily report from an independent component

### ISSUE THREAD

**Issue by salomondush** [ChangePlusPlusVandy/UFAR-frontend#5]
For functionality issues, it's a pain to have the daily form component rendered at the same time as other nurse app components. The current functionality is that when you click the new report button it sets active pages to display the first component of the reports. However, this might be a problem if we want to reuse the daily component for other purposes, such as validation.

I am suggesting two changes:
- Detach the `+ new Report` button from the daily report component and move it to the nurse landing page. 
- Make the daily report form independent, which is rendered separately when that button is clicked.

Since during validation, a validator will go through each form field by field, it will be easier to render the DailyReportForm component independently and re-populate all states with information from the report being validated. 

Also, since after every submission, we have to reset all states to their initial values using a very long function, we won't have to do that with this change. Since all states are re-initialized to their default values, every time we render the DailyFormComponent.

**Comment by ethanratnofsky** [comment]
Create new NewReportForm component:
- has single "active" boolean state variable
- if "active" state variable is true, render DailyReportForm; otherwise, render "New Report" button
- edit DailyReportForm component to initialize active page to "Identification" page and get rid of styling for "New Report" button
