### ISSUE TITLE
Missing fields on the first page of daily report form

### ISSUE THREAD

**Issue by sangalvs** [ChangePlusPlusVandy/UFAR-frontend#50]
We have 3 missing fields that are supposed to be in the daily report form on the first page. 

Here is the document where you can find these 3 fields (ignore the side comments, does not need to be autofill):  https://drive.google.com/file/d/1DUpTBaR1mPR7iM4-Uo4we6N4ZnJONoTx/view?usp=sharing

Field 1.6: Number of villages/communities in the health area (should be pre-populated and unable to be edited, should pull this number by counting the number of villages in the list after the health area is selected. Reach out if you have any questions about this)

Field 1.8: GPS Playback (Should be able to enter their location OR if you'd like, can automatically pull their coordinates. Needs to function offline though, which might be a little more challenging. For this one, you can either create a new field or just get the coordinates behind the scenes and store them in a state.)

Field 1.9 and 1.10: Date of Entry (just have this be in a date picker)

Here is the French translation for these fields: 

- Nombre de villages/communautés de l’aire de santé
- Lecture GPS
- Heure et Date de la saisie

**Comment by salomondush** [comment]
Need confirmation on the GPS field

**Comment by salomondush** [comment]
check #74 for a separate GPS feature. I am closing this in the meantime.
