### ISSUE TITLE
Number of treatment cycles for all treatments

### ISSUE THREAD

**Issue by salomondush** [ChangePlusPlusVandy/UFAR-frontend#52]
From the image below, we only have the number of cycles for the first 2 treatments. The rest are just check box fields without a field to put the number of cycles. 

<img width="349" alt="Screen Shot 2022-04-10 at 12 34 13 AM" src="https://user-images.githubusercontent.com/63796975/162603004-c044efca-306b-4b3a-a158-7a2b700212b0.png">

This is how it's portrayed in the form obtained from stakeholders
![Screen Shot 2022-04-10 at 12 36 35 AM](https://user-images.githubusercontent.com/63796975/162603044-1cf86dcd-d6df-472b-a048-be6a86b86cad.png)

**Comment by sparkeGH** [comment]
Resolved in branch ParkerMayIssues. Schistosomiasis, soil-transmitted helminthiasis, and trachoma now display a treatment cycle input field and two checkboxes as outlined by the example of onchocerciasis.
