### ISSUE TITLE
Daily Report Form - Percentages error on the Treatment Page

### ISSUE THREAD

**Issue by sangalvs** [ChangePlusPlusVandy/UFAR-frontend#56]
Refer to the "Total Couvert" field. Should be rounded to one decimal place also.

<img width="315" alt="Screen Shot 2022-04-13 at 12 42 13 AM" src="https://user-images.githubusercontent.com/65631510/163108307-31d452e1-9ff6-4afa-ada1-997ffe663388.png">

**Comment by sparkeGH** [comment]
Resolved in branch ParkerMayIssues.
Problem arises from a lack of bounds checking on user input. The user has the ability to enter negative population size, as well as population sizes smaller than the number of people treated. This causes the total coverage calculation to exceed the normal bounds of percentages. The revised version displays the default of 0% established by non-finite calculations in both cases of percentages less than 0 and greater than 100.
