### ISSUE TITLE
Wrong percentages for the Therapeutic coverage dashboard

### ISSUE THREAD

**Issue by salomondush** [ChangePlusPlusVandy/UFAR-frontend#61]
We are getting percentages that are more than 100 on the therapeutic dashboard. 

![Screen Shot 2022-04-30 at 1 37 35 AM](https://user-images.githubusercontent.com/63796975/166095164-39ca4bfd-d428-4e37-8290-770d993922c5.png)

According to the therapeutic coverage for Albendazole from the screenshot below, this might be bcs the total number of children treated for albendazole is way higher than the grand total of children 5-14 years enumerated. 
![Screen Shot 2022-04-30 at 1 42 12 AM](https://user-images.githubusercontent.com/63796975/166094971-02616288-747b-47bc-af14-6ea440ec2f41.png)

For the frontend, I would suggest, finding a way to make sure it doesn't happen. Displaying a pop-up with the relevant message, such as "Can't be higher than the total" would be very helpful. We can reuse the pop-up component that we are already using in the application.

**Comment by sangalvs** [comment]
For this one, I think this is an exact case where the validation will come in handy from the admin side. I think we can leave this feature for now, unless it is easy to implement.

**Comment by salomondush** [comment]
Sounds about right. I'll mark this as a draft.
